language: php

sudo: false

php:
  - "5.5"
  - "5.6"
  - "7"
  - "hhvm"

matrix:
  allow_failures:
    - php: "7"
    - php: "hhvm"

before_install: composer self-update

install: composer install

script: ./bin/phpunit --coverage-clover=build/logs/clover.xml

after_script: ./bin/coveralls
