language: php

sudo: false

php:
  - "7"
  - "7.1"

before_install: composer self-update

install: composer install

script: ./bin/phpunit --coverage-clover=build/logs/clover.xml

after_script: ./bin/coveralls
